df <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, colClasses = "character", na.strings = "?")
df<- subset(df, Date  %in% c("1/2/2007","2/2/2007"))
df$Date <- as.Date(df$Date, "%d/%m/%Y")
df$Time <- chron (times = df$Time)
png(filename="my_hist_2.png", width = 480, height = 480)
hist(df$Global_active_power, main = "Global Active Power", xlab = "Global Active Power (kilowatts)", col = "red", breaks = 12)
dev.off()