df <- read.table("household_power_consumption.txt", sep = ";", header = TRUE, colClasses = "character", na.strings = "?")
df<- subset(df, Date  %in% c("1/2/2007","2/2/2007"))
df$Date <- as.Date(df$Date, "%d/%m/%Y")
df$Time <- chron (times = df$Time)
df$Data_Time <- as.POSIXct(paste(df$Date, df$Time), format="%Y-%m-%d %H:%M:%S")
png(filename="plot4.png", width = 480, height = 480)
par(mfrow=c(2,2))
plot(df$Data_Time, df$Global_active_power,type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
plot(df$Data_Time, df$Voltage,type = "l", xlab = "datetime", ylab = "Voltage")
plot(df$Data_Time, df$Sub_metering_1, type = "l", xlab = "", ylab = "Energy sub metering")
lines(df$Data_Time, df$Sub_metering_2, type = "l", col="red")
lines(df$Data_Time, df$Sub_metering_3, type = "l", col="blue")
legend ("topright", pch ="_", col = c("black", "red", "blue"), legend = c("Sub-metering_1", "Sub-metering_2", "Sub-metering_3"))
plot(df$Data_Time, df$Global_reactive_power,type = "l", xlab = "datetime", ylab = "Global reactive power")
dev.off()